# Generated by Django 3.2.4 on 2021-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storedJSON', models.JSONField()),
                ('deletionTime', models.DateTimeField()),
            ],
        ),
    ]
