# Generated by Django 3.2.4 on 2021-06-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='randomjson',
            name='storedJSON',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=2048)),
                ('descriptors', models.ManyToManyField(to='RJS.LinkedDescriptor')),
            ],
        ),
    ]
